### ISSUE TITLE
`Can't find our webpack executable at` on Heroku

### ISSUE THREAD

**Issue by bitscraps** [febeling/webpack-rails-buildpack#13] opened 2017-06-01 17:30 UTC
On thursday we started receiving this issue during the slug compilation on heroku.

** Execute webpack:compile
rake aborted!
Can't find our webpack executable at /tmp/build_8f0a62a90132b53a9b4b0536055c0a88/node_modules/.bin/webpack - have you run npm install?

Are there any issues you were aware of.  Heroku are saying its an issue with the build pack and not heroku.

These are our current build packs:

1. https://github.com/sofarsounds/heroku-buildpack-git-sha.git
2. heroku/ruby
3. heroku/nodejs
4. https://github.com/febeling/webpack-rails-buildpack.git

As mentioned these were working but are not now.

**Comment by febeling** [comment] 2017-06-01 19:02
Sounds like something has changed on the Heroku platform. Is someone following their changes announcements?

**Comment by bitscraps** [comment] 2017-06-01 20:39
Just to provide some information this fork of you build pack works https://github.com/booqable/webpack-rails-buildpack, I'm not sure which commits resolve the issue however.

**Comment by febeling** [comment] 2017-06-02 11:30
The diff is small - https://github.com/febeling/webpack-rails-buildpack/compare/master...booqable:master

The problem might be due to you keeping `webpack` as a `dependencies` entry in the packages.jon, not under `devDependiencies`. Can you confirm that?

**Comment by bitscraps** [comment] 2017-06-02 11:34
Thanks it is in fact under dependencies and not devDependencies.  I thought it would be a dependency and not a dev dependency however may have misunderstood.  perhaps this could be clearer in the readme, it seems that this did not matter earlier on the week on heroku but now does.

**Comment by febeling** [comment] 2017-06-02 11:43
I became aware of this gotcha only now, sorry. And it's curious that it worked before. 

Anyway, can you confirm that it's working with that change? 

I'll put a note in the README to save other (and my future self) to get confused by this again.

**Comment by bitscraps** [comment] 2017-06-02 11:44
Im currently using a fork where all dependencies are being installed and that works.  I will try moving web pack  into devdependencies and switching back next week and let you know.

**Comment by febeling** [comment] 2017-06-02 11:47
Ok, thanks. But I'll leave out the note until this hunch of mine is confirmed. Definitely interested to hear if that change has this effect.

**Comment by febeling** [comment] 2017-06-02 15:27
Ok, I have the same problem with my app. I'm gonna pull the commit from booqable.

**Comment by febeling** [comment] 2017-06-02 15:32
Assuming cherry-picking 67cdc01bd28f2793e86a406e442c97dbaad4cf0e solved the problem. Please tell me if this solves the error @bitscraps, if you get a chance.

**Comment by roshiro** [comment] 2017-06-07 20:41
Hi @febeling / @bitscraps 

I had the same issue and adding the ` --only=dev` to `npm install` solved the issue for me. This is my `bin/compile` [diff](https://github.com/roshiro/webpack-rails-buildpack/commit/dca276bebf896547fd2f979a9d3f725138596138)

**Comment by febeling** [comment] 2017-06-08 13:41
@roshiro that's the exact change I applied as well. Thanks for confirming that, it's very helpful.

**Comment by febeling** [comment] 2017-06-09 20:39
With @roshiro's confirmation I'm closing this now. Please reopen in case.

**Closed as completed by febeling** 2017-06-09 20:39 UTC
